<?php

/**
 * @file
 * OCHA shared logic.
 */

/**
 * Implements hook_theme().
 */
function ocha_search_theme($existing, $type, $theme, $path) {
  return [
    'ocha_search_block' => [
      'template' => 'ocha-search-block',
      'variables' => [
        'results_page_path' => NULL,
      ],
    ],
    'ocha_search_results_page' => [
      'template' => 'results-page',
      'variables' => [
        'title' => NULL,
        'search_text' => NULL,
        'gcse_id' => NULL,
        'scope' => NULL,
        'enable_ocha_wide_results' => NULL,
        'toggle_link_site_text' => NULL,
        'toggle_link_ocha_text' => NULL,
        'toggle_link_path' => NULL,
      ],
    ],
  ];
}
