<?php

/**
 * @file
 * OCHA shared logic.
 */

/**
 * Implements hook_theme().
 */
function ocha_search_theme($existing, $type, $theme, $path) {
  return [
    'ocha_search_results_page' => [
      'template' => 'results-page',
      'variables' => [
        'title' => NULL,
        'search_text' => NULL,
        'gcse_id' => NULL,
        'toggle_link_text' => NULL,
        'toggle_link_path' => NULL,
      ],
    ],
  ];
}
